### ISSUE TITLE
type object not scriptable

### ISSUE THREAD

**Issue by saiv123** [fabaindaiz/Spellsolver#21]
on python 3.8.10

`Traceback (most recent call last):
  File "graphicui.py", line 2, in <module>
    from src.interfaces.tkinterboard import TkinterBoard
  File "C:\Users\saiv2\Downloads\Spellsolver-1.8\Spellsolver-1.8\src\interfaces\tkinterboard.py", line 1, in <module>
    from src.interfaces.tkinterwidget import Board
  File "C:\Users\saiv2\Downloads\Spellsolver-1.8\Spellsolver-1.8\src\interfaces\tkinterwidget.py", line 4, in <module>
    from src.modules.resultlist import ResultWord
  File "C:\Users\saiv2\Downloads\Spellsolver-1.8\Spellsolver-1.8\src\modules\resultlist.py", line 2, in <module>
    from src.modules.gameboard import GameTile
  File "C:\Users\saiv2\Downloads\Spellsolver-1.8\Spellsolver-1.8\src\modules\gameboard.py", line 2, in <module>
    from src.utils.utils import get_coordinate, letter_points, valid_word
  File "C:\Users\saiv2\Downloads\Spellsolver-1.8\Spellsolver-1.8\src\utils\utils.py", line 3, in <module>
    def get_coordinate(aux_cord: int) -> tuple[int]:
TypeError: 'type' object is not subscriptable`

**Comment by fabaindaiz** [comment]
I still have to test that everything works well, but in theory the bug has already been fixed.
The pull request should be closed within the next few days.
